USE [master]
GO
/****** Object:  Database [BusTrackingDB]    Script Date: 11/27/2025 11:10:02 PM ******/
CREATE DATABASE [BusTrackingDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BusTrackingDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BusTrackingDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BusTrackingDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BusTrackingDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BusTrackingDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BusTrackingDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BusTrackingDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BusTrackingDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BusTrackingDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BusTrackingDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BusTrackingDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [BusTrackingDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BusTrackingDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BusTrackingDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BusTrackingDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BusTrackingDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BusTrackingDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BusTrackingDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BusTrackingDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BusTrackingDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BusTrackingDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BusTrackingDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BusTrackingDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BusTrackingDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BusTrackingDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BusTrackingDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BusTrackingDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BusTrackingDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BusTrackingDB] SET RECOVERY FULL 
GO
ALTER DATABASE [BusTrackingDB] SET  MULTI_USER 
GO
ALTER DATABASE [BusTrackingDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BusTrackingDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BusTrackingDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BusTrackingDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BusTrackingDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BusTrackingDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'BusTrackingDB', N'ON'
GO
ALTER DATABASE [BusTrackingDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [BusTrackingDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BusTrackingDB]
GO
/****** Object:  Table [dbo].[Buses]    Script Date: 11/27/2025 11:10:02 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Buses](
	[BusID] [bigint] NOT NULL,
	[BusName] [nvarchar](50) NOT NULL,
	[DriverID] [int] NULL,
	[Route] [nvarchar](100) NULL,
	[Position] [geography] NULL,
PRIMARY KEY CLUSTERED 
(
	[BusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Contacts]    Script Date: 11/27/2025 11:10:02 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contacts](
	[ContactID] [bigint] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[Phone] [nvarchar](20) NULL,
	[Message] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ContactID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Drivers]    Script Date: 11/27/2025 11:10:02 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Drivers](
	[DriverID] [int] NOT NULL,
	[DriverName] [nvarchar](50) NOT NULL,
	[Phone] [nvarchar](20) NULL,
	[LicenseNumber] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[DriverID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Feedback]    Script Date: 11/27/2025 11:10:02 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Feedback](
	[FeedbackID] [bigint] NOT NULL,
	[UserName] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[Message] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[FeedbackID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 11/27/2025 11:10:02 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Buses]  WITH CHECK ADD FOREIGN KEY([DriverID])
REFERENCES [dbo].[Drivers] ([DriverID])
GO
USE [master]
GO
ALTER DATABASE [BusTrackingDB] SET  READ_WRITE 
GO
